import argparse


def get_args():
    parser = argparse.ArgumentParser(description="train a model on LLP data")
    # required:
    parser.add_argument("-d", "--data_path", nargs='?', required=True,
                        help="path to the label proportion dataset generated by make_data.py")
    parser.add_argument("-c", "--num_classes", nargs='?', type=int, required=True, metavar="10",
                        help="number of classes")

    # optional:
    parser.add_argument("-a", "--algorithm", nargs='?', choices=["llpfc"], default="llpfc",
                        help="choose a training algorithm")  # ToDo: add more after implementing competitors
    parser.add_argument("-n", "--network", nargs='?', choices=["wide_resnet_28_2", "llpgan_dis", "nin"],
                        default="wide_resnet_28_2", help="the neural network model")
    parser.add_argument("--drop_rate", nargs="?", type=float, default=0.3,
                        help="the drop rate in dropout layers, for wide resnet")  # add more to this
    parser.add_argument("-l", "--lr", nargs="?", type=float, default=1e-1, help="learning rate of SGD")
    parser.add_argument("-m", "--momentum", nargs="?", type=float, default=0.3, help="momentum of SGD")
    parser.add_argument("-e", "--total_epochs", nargs="?", type=int, default=400,
                        help="total number of epochs to train")
    parser.add_argument("-r", "--num_epoch_regroup", nargs="?", type=int, default=20,
                        help="groups will be regenerated every this number of epochs, " 
                             "only effective if the algorithm is llpfc")
    parser.add_argument("-v", "--validate", nargs='?', type=bool, default=False,
                        help="if True, then validate on 10%% of the training data set; " 
                             "if False, output testing loss and accuracy will training")
    parser.add_argument("--train_batch_size", nargs='?', type=int, default=128, help="training batch size")
    parser.add_argument("--test_batch_size", nargs="?", type=int, default=256, help="test batch size")
    parser.add_argument("-p", "--save_path", nargs='?', default=None,
                        help="path to save the trained model, model will not be saved if the path is None")
    return parser.parse_args()


def main(args):
    pass


if __name__ == "__main__":
    args = get_args()
    main(args)